# Generated by Django 2.2.2 on 2020-09-18 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0003_auto_20200908_2144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='is_activate',
            new_name='is_active',
        ),
    ]
